defmodule Accountkit.Repo.Migrations.ScopedRoles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:platform_roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "platform_roles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create constraint(:platform_roles, :platform_roles_role_check,
             check: "role IN ('platform_owner')"
           )

    create unique_index(:platform_roles, [:user_id, :role],
             name: "platform_roles_unique_user_platform_role_index"
           )

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:name], name: "organizations_unique_name_index")

    create table(:organization_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "organization_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "organization_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create constraint(:organization_memberships, :organization_memberships_role_check,
             check: "role IN ('org_admin')"
           )

    create unique_index(:organization_memberships, [:organization_id, :user_id],
             name: "organization_memberships_org_user_index"
           )
  end

  def down do
    drop constraint(:organization_memberships, "organization_memberships_organization_id_fkey")

    drop constraint(:organization_memberships, "organization_memberships_user_id_fkey")

    drop_if_exists unique_index(:organization_memberships, [:organization_id, :user_id],
                     name: "organization_memberships_org_user_index"
                   )

    drop table(:organization_memberships)

    drop_if_exists unique_index(:organizations, [:name], name: "organizations_unique_name_index")

    drop table(:organizations)

    drop constraint(:platform_roles, "platform_roles_user_id_fkey")

    drop_if_exists unique_index(:platform_roles, [:user_id, :role],
                     name: "platform_roles_unique_user_platform_role_index"
                   )

    drop table(:platform_roles)
  end
end
