defmodule Accountkit.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:rate_limit_policies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :limit, :bigint, null: false
      add :period_seconds, :bigint, null: false
      add :enabled, :boolean, null: false, default: true
      add :description, :text
    end

    create unique_index(:rate_limit_policies, [:key],
             name: "rate_limit_policies_unique_key_index"
           )
  end

  def down do
    drop_if_exists unique_index(:rate_limit_policies, [:key],
                     name: "rate_limit_policies_unique_key_index"
                   )

    drop table(:rate_limit_policies)
  end
end
