defmodule Accountkit.Repo.Migrations.OrganizationTextLogo do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :text_logo, :text
    end

    execute """
    UPDATE organizations
    SET text_logo = left(name, 32)
    WHERE text_logo IS NULL
    """

    alter table(:organizations) do
      modify :text_logo, :text, null: false
    end
  end

  def down do
    alter table(:organizations) do
      remove :text_logo
    end
  end
end
